// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcIItxZMWXpdvi3jVpDoVVfPdOOYecLsI',
    appId: '1:979566347087:web:81cf29a722b425da72fb3a',
    messagingSenderId: '979566347087',
    projectId: 'zc-tasks',
    authDomain: 'zc-tasks.firebaseapp.com',
    storageBucket: 'zc-tasks.appspot.com',
    measurementId: 'G-1G00RB0YWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbO8RdoUAcIpocZnVm9khztRHiE6yfujc',
    appId: '1:979566347087:android:77987b937eaeaa7172fb3a',
    messagingSenderId: '979566347087',
    projectId: 'zc-tasks',
    storageBucket: 'zc-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlWRp1A5nrwlViFQ5fKNyNPUR9Jn7czI',
    appId: '1:979566347087:ios:4494e30f7ba0f69772fb3a',
    messagingSenderId: '979566347087',
    projectId: 'zc-tasks',
    storageBucket: 'zc-tasks.appspot.com',
    iosBundleId: 'com.example.zcTasks',
  );
}
